import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "./components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex gap-3  antialiased`}
    >
     <Sidebar/>
      <main className="flex-1">{children}</main>
    
    </div>
  );
}
